service: gbc-ml-document-classifier

plugins:
  - serverless-wsgi
  - serverless-python-requirements
custom:
  wsgi:
    app: api.app
    packRequirements: False
  pythonRequirements:
    dockerizePip: true
    zip: true

package:
  exclude:
    - node_modules/**
    - .idea/**
    - .requirements/**
    - env/**
    - README.md
    - package.json
    - package-lock.json
    - requirements.txt

provider:
  name: aws
  runtime: python3.6
  region: eu-west-1
  environment:
    ENV_ACCESS_KEY_ID: ${env:AWS_ACCESS_KEY_ID}
    ENV_SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY}
    ENV_AWS_BUCKET: ${env:S3_BUCKET_NAME}

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
